version: 2
jobs:
  build:
    # docker-composeがインストール済みの仮想マシンをプル
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - restore_cache:
        key: yarn-{{ checksum "yarn.lock"}}
      - run:
          name: Dockerコンテナの起動
          command: docker-compose -f dev-docker-compose.yml up -d
      - save_cache:
        key: yarn-{{ checksum "yarn.lock"}}
        paths:
          - node_modules
      # - run:
          # name: Dockerコンテナのビルド
          # command: docker-compose -f dockertest/docker-compose.test.yml build
      # - run:
      #     name: Dockerコンテナの起動
      #     command: docker-compose -f dockertest/docker-compose.test.yml up -d
      # - run:
      #     name: db接続を待機
      #     command: sleep 10
      # - run:
      #     name: データベースのセットアップ
      #     command: docker-compose -f dockertest/docker-compose.test.yml exec web bundle exec rails db:migrate RAILS_ENV=test
      # - run:
      #     name: Dockerコンテナの停止
      #     command: docker-compose -f dockertest/docker-compose.test.yml down